version: "3"
services:
  ui-react:
    build:
      context: ./ui-react  # Path to the directory containing the React UI Dockerfile
    ports:
      - "3000:3000"  # Map host port 3000 to container port 3000 for the React UI

  microservices-api:
    build:
      context: ./microservices-api  # Path to the directory containing the FastAPI Dockerfile
    ports:
      - "8080:8080"  # Map host port 8080 to container port 8080 for the FastAPI microservices

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data:

networks:
  frontend-backend-network:
    driver: bridge